version: '3'
services:
  db:
    container_name: test
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: test-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db